### ISSUE TITLE
Useful links

### ISSUE THREAD

**Issue by NixFrog** [ClubNix/academy#3]
A tab "useful links" regroups... Useful links !!!
The links have categories and consultation dates. Like that, it will be easier for new members to sort depreciated tutorials later.

**Comment by minijackson** [comment]
I don't know if it's a good idea, it's kind of not the purpose of the application…

**Comment by minijackson** [comment]
Could make another application that serves partially that purpose though

**Comment by NixFrog** [comment]
If the application is only aimed at members looking for other members then indeed it would be useless. However, as such lists are always useful for new members, we can always make a blog post about it. I still think a beginner would really appreciate easily knowing where to get advanced information.

**Comment by pacien** [comment]
These suggestions should be customized according to the user's skills and browsing history.
